import { API_ENDPOINTS } from "@/configs/api.endpoints.config.ts";
import type DiplomaCreation from "@/features/class-creation/components/DiplomaCreation/DiplomaCreation.tsx";

export const diplomaCreationInputControllers = [
  {
    task: "new-degree-item-field",
    name: "diplomaFieldId",
    label: "Métier / Domaine du diplôme",
    placeholder: "Sélectionnez...",
    creationButtonText: "Ajouter un métier ou domaine",
    useButtonAddNew: true,
    useCommands: true,
    type: "text",
    apiEndpoint: API_ENDPOINTS.GET.DEGREES.endpoints.FIELD,
    dataReshapeFn: API_ENDPOINTS.GET.DEGREES.dataReshape,
    id: "diploma-field-input",
  },
  {
    task: "new-degree-item-year",
    name: "yearId",
    label: "Année scolaire",
    placeholder: "Sélectionnez...",
    creationButtonText: "Ajouter une année scolaire",
    useButtonAddNew: true,
    type: "text",
    useCommands: true,
    apiEndpoint: API_ENDPOINTS.GET.DEGREES.endpoints.YEAR,
    dataReshapeFn: API_ENDPOINTS.GET.DEGREES.dataReshape,
    id: "school-year-input",
  },
  {
    task: "new-degree-item-degree",
    name: "levelId",
    label: "Diplôme / Niveau scolaire",
    placeholder: "Sélectionnez...",
    creationButtonText: "Ajouter un niveau scolaire",
    useButtonAddNew: true,
    useCommands: true,
    type: "text",
    apiEndpoint: API_ENDPOINTS.GET.DEGREES.endpoints.LEVEL,
    dataReshapeFn: API_ENDPOINTS.GET.DEGREES.dataReshape,
    id: "school-level-input",
  },
  {
    id: "add-module-skills",
    apiEndpoint: API_ENDPOINTS.GET.SKILLS.endPoints.MODULES,
    dataReshapeFn: API_ENDPOINTS.GET.SKILLS.dataReshape,
    task: "new-degree-module",
    name: "modulesList",
    title: "Modules",
    type: "button",
    useButtonAddNew: true,
    creationButtonText: "Ajouter un module",
    useCommands: true,
    placeholder: "Recherchez des modules...",
  },
] satisfies Parameters<typeof DiplomaCreation>[0]["inputControllers"];
